---
name: idr0063-newman-chromosomalloci/experimentA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: no
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split: ","
  # Should this column be included in the clients (yes/no)
  includeclient: yes
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: yes
  # Should empty values be omitted from the client display
  omitempty: yes

columns:
  - name: Characteristics [Strain]
    clientname: Strain
    include: true

  - name: Experimental Condition [Time Point]
    clientname: Time Point
    include: true

  - name: Assay Quality Control
    clientname: Assay Quality Control
    include: true

  - name: Image Quality Control
    clientname: Image Quality Control
    include: true

  - name: Comment [Image File Comments]
    clientname: Image File Comments
    include: true

  - name: Channels
    clientname: Channels
    include: true

  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
      - name: Comment [Gene Identifier]
        clientname: Gene Identifier
        include: yes
      - name: Comment [Gene Identifier]
        clientname: Gene Identifier URL
        clientvalue: https://www.ncbi.nlm.nih.gov/gene/{{ value|urlencode }}
        include: yes
      - name: Comment [Gene Symbol]
        clientname: Gene Symbol
        include: yes

advanced:
  well_to_images: yes
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/gene
      keys:
        - Gene Identifier
        - Gene Symbol
